export const decks = [
  {
    name: 'Wrong Answer Cards',
    cards: [
      { id: 1, questions: ["Which form factor provides a mini card interface used to connect a laptop's SSD at higher bus speeds than SATA?"], answers: ["M.2"] },
      { id: 2, questions: ["You are trying to select the best device to install to proactively stop outside attackers from reaching your internal network. Which device would be the BEST for you to select?"], answers: ["IPS (Intrusion Prevention System)"] },
      { id: 3, questions: ["Does 5.0 GHz wireless frequency have more channels than 2.4GHz?", "Two advantages of 2.4GHz?"], answers: ["Yes", "Ability to penetrate solid surfaces and has a longer range"] },
      { id: 4, questions: ["A cybersecurity analyst wants to install a network appliance to conduct packet capturing of the network traffic between the router and the firewall on the network. The device should not be installed in line with the network, so it must receive a copy of all traffic flowing to or from the firewall. Which tool is required to meet these requirements?", "define network tap"], answers: ["Network Tap", " A network tap is used to create a physical connection to the network that sends a copy of every packet received to a monitoring device for capture and analysis."] },
      { id: 5, questions: ["Dion Training has just installed a brand new email server. Which DNS records would need to be created to allow the new server to receive email on behalf of diontraining.com?", "What is an MX record used for?"], answers: ["MX", "An MX record is used for outgoing (SMTP) and incoming (POP3/IMAP) traffic."] },
      { id: 6, questions: ["802.11a"], answers: ["5 GHz - 54 Mbps"] },
      { id: 7, questions: ["802.11b"], answers: ["2.4 GHz - 11 Mbps"] },
      { id: 8, questions: ["802.11g"], answers: ["2.4 GHz - 54 Mbps"] },
      { id: 9, questions: ["802.11n (WIFI 4) Band and Bandwith"], answers: ["2.4 and 5 GHz - 150 Mbps / 600 Mbps (MIMO)"] },
      { id: 10, questions: ["802.11ac (WIFI 5) Band and Bandwith"], answers: ["5 GHz - 3.5 Gbps (MU-MIMO)"] },
      { id: 11, questions: ["802.11ax (WIFI 6) Band and Bandwith"], answers: ["2.4, 5, and 6 GHz - 9.6 Gbps (MU-MIMO)"] },
      { id: 12, questions: ["Which network type would be used to create a dedicated, independent high-speed network to interconnect and share pools of storage devices to multiple servers?"], answers: ["Storage Area Network (SAN)"] },
      { id: 13, questions: ["Which network standard allows a networking device to provide up to 15.4W of power to a connected device?"], answers: ["802.3af"] },
      { id: 14, questions: ["Which connector type used to connect the TV tuner to the wall jack when using a coaxial cable?"], answers: ["F-type"] },
      { id: 15, questions: ["A customer wants to build a home server that would allow their family to stream locally stored video files on a home network. The home server should also have fault tolerance to ensure the server's data is not inadvertently lost in the event of a hard disk drive failure. Do you agree that a Gigabit NIC and RAID setup would be good choices?"], answers: ["Yes. In this scenario, a gigabit NIC will help handle the heavy network load created by sharing large files over the network. Data protection needs to use a RAID 1, RAID 5, or RAID 10 configuration to protect against any potential data loss caused by a single hard disk drive failure. "] },
      { id: 16, questions: ["What is used to connect Cat 5e or above networks in an MDF or IDF?", "Not?"], answers: ["110 punchdown block", "66 punchdown block"] },
      { id: 17, questions: ["What is a DB-9 connector used to terminate?"], answers: ["an RS-232 serial cable"] },
      { id: 18, questions: ["When should you try to replace a power supply's fan?"], answers: ["Never. If the fan in the power supply is faulty, replace the entire power supply. You should never attempt to repair or fix a broken power supply or broken power supply cooling fan due to the power supply's high voltage electrical components. When a fan creates a grinding sounds, this is evidence of an impending failure and the device needs to be replaced. Technicians should never open a power supply or replace any of its internal components, therefore the entire power supply should be replaced in this scenario. "] },
      { id: 19, questions: ["You have been assigned a trouble ticket for a workstation that is unable to boot. When you arrive at the workstation, you recognize an error message on the screen that reads, 'Error loading operating system, BOOTMGR is missing, Press Ctrl + Alt + Del to restart.' What action should you take first?"], answers: ["Reboot the computer into the Windows 10 repair console and enter 'Bootrec/fixmbr' at the command prompt"] },
      { id: 20, questions: ["Is NVMe a type of SSD?"], answers: ["Yes, and it provides better performance than the original types"] },
      { id: 21, questions: ["Which type of RAID should be used for a virtualization server that must have the fastest speed and highest redundancy level?"], answers: ["RAID 10"] },
      { id: 22, questions: ["Cat5 Distance and Bandwidth"], answers: ["100 meters / 100 Mbps"] },
      { id: 23, questions: ["Cat5e Distance and Bandwidth"], answers: ["100 meters / 1 Gbps"] },
      { id: 24, questions: ["Cat6 Distance and Bandwidth"], answers: ["100 meters / 1 or 10 Gbps"] },
      { id: 25, questions: ["Cat6a Distance and Bandwidth"], answers: ["100 meters / 10 Gbps"] },
      { id: 26, questions: ["Cat7 Distance and Bandwidth"], answers: ["100 meters / 10 Gbps"] },
      { id: 27, questions: ["Cat8 (Fast Ethernet) Distance and Bandwidth"], answers: ["30 meters / 40 Gbps"] },
      { id: 28, questions: ["What cable types are used for coaxial cables?"], answers: ["RG-6 and RG-59"] },
      { id: 29, questions: ["A virtual machine has more downtime than a physical machine?"], answers: ["false, it has less downtime"] },
      { id: 30, questions: ["Who can each of these types of network connection communicate with (for VMs)? External, Internal and VMs, Private, Localhost"], answers: ["internet, host, private VM network, itself"] },
      // port flashcards
      { id: 31, questions: ["PORTS: File Transfer Protocol (FTP)", "Port 21 mainly used for?", "Port 20 mainly used for?", "Is it secure?"], answers: ["20/21", "file management", "data transfer", "not secure, transmits in plain text"] },
      { id: 32, questions: ["PORTS: Secure Shell (SSH)", "use?"], answers: ["22", "Connection-oriented protocol used to setup SECURE Telnet connections for remote logins"] },
      { id: 33, questions: ["PORTS: Telnet", "use?"], answers: ["23", "Telnet is a terminal emulation program that allows for remote access to text on another computer. Telnet is NOT SECURE and transmits plaintext"] },
      { id: 34, questions: ["PORTS: Simple Mail Transfer Protocol (SMTP)", "use?"], answers: ["25", "Simple Mail Transfer Protocol (SMTP) is used to send email only and is a push protocol"] },
      { id: 35, questions: ["PORTS: Domain Name System (DNS)", "use?"], answers: ["53", "The DNS is used to resolve hostnames to IP addresses"] },
      { id: 36, questions: ["PORTS: Dynamic Host Configuration Protocol (DHCP)", "use?", "port for client/server?"], answers: ["67/68", "DHCP assigns IP addresses dynamically to network clients", "68/67"] },
      { id: 37, questions: ["PORTS: Hypertext Transfer Protocol (HTTP)", "use?"], answers: ["80", "HTTP manages communications between a web server and a client to view internet content. HTTP is NOT SECURE and transmits in plain text"] },
      { id: 38, questions: ["PORTS: Post Office Protocol (POP3)", "use?"], answers: ["110", "POP3 is used for downloading email"] },
      { id: 39, questions: ["PORTS: Network Basic Input/Output System (NetBIOS)/NetBIOS over TCP/IP(NetBT)", "use?"], answers: ["137/139", "An API for communication between computers over a network. NetBIOS works over OSI layer 4 and needs to work with a layer 5 protocol, namely TCP/IP, to function properly. NetBIOS over TCP/IP is called NetBT"] },
      { id: 40, questions: ["PORTS: Internet Message Access Protocol (IMAP)", "use?"], answers: ["143", "IMAPis currently in its fourth version and is used for downloading email. IMAP4 is SECURE"] },
      { id: 41, questions: ["PORTS: Simple Network Management Protocol (SNMP)", "use?"], answers: ["161/162", "SNMP is used for network management. 161 for sending and receiving requests and port 162 for receiving transmissions from managed devices"] },
      { id: 42, questions: ["PORTS: Lightweight Directory Access Protocol (LDAP)", "use?"], answers: ["389", "LDAP is used for accessing information stored in an information directory"] },
      { id: 43, questions: ["PORTS: Hypertext Transfer Protocol Secure (HTTPS)", "use?"], answers: ["443", "HTTPS is the SECURE version of HTTP"] },
      { id: 44, questions: ["PORTS: Server Message Block (SMB)/Common Internet File System (CIFS)", "use?"], answers: ["445", "SMB is primarily a Microsoft protocol used for shared file access. CIFS is an enhanced version of SMB"] },
      { id: 45, questions: ["PORTS: Remote Desktop Protocol (RDP)", "use?"], answers: ["3389", "RDP allows for remote connection to computers"] },
      { id: 46, questions: ["TCP", "reliable?"], answers: ["Transmission Control Protocol", "yes, because the receiving host acknowledges that is received the data"] },
      { id: 47, questions: ["UDP", "reliable?"], answers: ["User Datagram Protocol (UDP)", "no, but it is faster than TCP for this reason"] },
      // need flashcards on USB specs
      { id: 48, questions: ["USB 1.1 Speed?"], answers: ["12 Mbps"] },
      { id: 49, questions: ["USB 2.0 Speed?"], answers: ["480 Mbps"] },
      { id: 50, questions: ["USB 3.0 Speed?"], answers: ["5 Gbps"] },
      { id: 51, questions: ["USB 3.1 Speed?"], answers: ["10 Gbps"] },
      { id: 52, questions: ["USB 3.2 Speed?"], answers: ["20 Gbps"] },
      { id: 53, questions: ["USB 4 Speed?"], answers: ["40 Gbps"] },
      { id: 54, questions: ["Thunderbolt Speed?"], answers: ["40 Gbps"] },
      { id: 55, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 56, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 57, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 58, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 59, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 60, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 61, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 62, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 63, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 64, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 65, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 66, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 67, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 68, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 69, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 70, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 71, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 72, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 73, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 74, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 75, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 76, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 77, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 78, questions: ["BLANK"], answers: ["BLANK"] },
      { id: 79, questions: ["BLANK"], answers: ["BLANK"] },
    ]
  },
  {
    name: 'Domain 1.0 Mobile Devices (and Laptops)', cards: [
      { id: 1, questions: ['Capacitive Touch Screen', 'True or False: One touch at a time?'], answers: ['Any touchscreen that works by seeing the distortion in an electrostatic field', 'True. A single tactile input is one touch at a time'] },
      { id: 2, questions: 'Multi-Touch Screen', answers: 'Can process two or more contact points simultaneously' },
      { id: 3, questions: ['What does LCD stand for?', 'What does it mean?'], answers: ['Liquid-Crystal Display', 'Uses liquid crystal where the properties can change with the application of voltage'] },
      { id: 4, questions: 'Explain Pixel (Picture Element)', answers: 'Individual point on a screen inside of a display' },
      { id: 5, questions: ['What is a TFT?', 'What is it referred to as?'], answers: ['A thin-film transistor', 'an LCD panel'] },
      { id: 6, questions: ['What is a Twisted Nematic (TN)?', "What's its advantage?"], answers: ['Contains crystals that twist or untwist in response to voltage being applied or removed', 'TN support fast response time in comparison to other TFT technologies and displays'] },
      { id: 7, questions: ['what does IPS stand for?', 'What does it do?', 'True or False: It support 180 degree viewing angles?'], answers: ['In-Plane Switching', 'Uses crystals that rotate to be able to deliver color', 'False. It can support 178degree horizontal and vertical viewing angles'] },
      { id: 8, questions: ['What is VA?', 'What is its advantage?'], answers: ['Vertical Alignment', 'A VA display has a contrast ratio of two to three times better than a standard IPS display'] },
      { id: 9, questions: ['What does CCFL stand for?', 'How does it work?', 'Does it require AC or DC voltage?'], answers: ['Cold Cathode Fluorescent Lamp', 'Lamp that sits behind the display and lights up the liquid crystal display to show the colors and images properly on screen', 'CCFL requires AC voltage'] },
      { id: 10, questions: ['What does LED mean?', 'what is it?', 'advantages?'], answers: ['Light-Emitting Diode', 'Newer form of light that uses direct current (DC)', 'use of LEDs use less power, leading to longer battery life and better performance'] },
      { id: 11, questions: ['What does OLED mean?', 'What are three differences to LED'], answers: ['Organic Light-Emitting Diode', 'Each pixel has its own separate LED that provides the light', 'OLEDs can be made from plastic', 'OLEDs can be folded, rolled up, or manipulated to create different shapes and sizes of displays'] },
      { id: 12, questions: ['What are the three main mobile device components?'], answers: ['Digitizer, Accelerometer, and Gyroscope'] },
      {
        id: 13, questions: ['What is the digitizer?', 'what is its purpose?'
        ], answers: ['layer sandwiched between protective glass and the display panel inside of a touchscreen display', 'Haptic feedback provides a form or touch responsiveness from the display back to the end-user']
      },
      { id: 14, questions: ['What is the accelerometer?'], answers: ['Combination device that uses hardware and software to measure the velocity, rotation, and shaking of a mobile device'] },
      { id: 15, questions: ['What is a gyroscope?', 'what are the reasons its an improvement?'], answers: ['An improved version of the basic accelerometer', 'Detects pitch (Y), roll (X), and yaw (Z). Performs actions and stabilizes images'] },
      { id: 16, questions: ['Name 5 out of 6 Mobile device accessories'], answers: ['Track pad, drawing pad, microphone, speaker, headset, digital camera'] },
      { id: 17, questions: ['What are the two types of pad devices that can be used with mobile?', 'What does the track pad do?'], answers: ['Track pad and Drawing pad', 'controls the cursor on the screen'] },
      { id: 18, questions: ['What two devices does an external headset combine?'], answers: ['headsets combine both the microphone and the speaker'] },
      { id: 19, questions: ['True of False: Wireless connectivity is slower on smaller devices than it is on larger devices?'], answers: ['True'] },
      { id: 20, questions: ['What are the two main types of wireless cellular technology?', 'What is the more powerful and flexible technology?'], answers: ['GSM and CDMA', 'CDMA'] },
      { id: 21, questions: ['What does PRL mean?', 'What does this contain?', 'True or False: restrictions vary based on model?'], answers: ['Preferred Roaming List', 'This contains all the information about different cellular towers', 'True'] },
      { id: 22, questions: ['What are the two types of short-range connection options for mobile?'], answers: ['Bluetooth and Near-Field Communication'] },
      { id: 23, questions: ['What are the four main types of wired mobile connectivity?'], answers: ['Lightning Cable (Apple), USB-C, DB9 Cable, Universal Asynchronous Receiver-Transmitter (UART)'] },
      { id: 24, questions: ['What is the difference between a port replicator and a docking station?'], answers: ['Port replicators are port mirrors and docking stations are a port mirror with ADDITIONAL points'] },
      { id: 25, questions: ['Which devices use Android and iOS, respectively?', 'Which is open-source, closed-source?'], answers: ['any non-Apple device, iPads and iPhones', 'Android is open, iOS is closed'] },
      { id: 26, questions: ['What programming languages do iOS apps use?', 'What programming languages do Android apps use?'], answers: ['Swift and Xcode', 'Java and Android Studio'] },
      { id: 27, questions: ['Benefit of Microsoft 365 to mobile?'], answers: ['Provides the ability to have office productivity software and a large amount of storage space in the cloud (OneDrive)'] },
      { id: 28, questions: ['Define Mobile Device Synchronization/Sync'], answers: ['Act of copying data back and forth between different devices'] },
      { id: 29, questions: ['What is a vCard?'], answers: ['Standard contact format and is widely supported by most address books and software applications'] },
      { id: 30, questions: ['Is POP3 a good choice for synchronization?'], answers: ['No, oldest format and does not support the synchronization across devices'] },
      { id: 31, questions: ['Which email protocols can manage the state of an email?'], answers: ['IMAP and Exchange'] },
      { id: 32, questions: ['What are the three synchrozation choices?'], answers: ['synchronization to the cloud, to the computer and with the automobile'] },
      { id: 33, questions: ['What is EMM?', 'Meaning?'], answers: ['Enterprise Mobility Management', 'Class of software designed to apply security policies for use on mobile devices'] },
      { id: 34, questions: ['What is MDM?', 'Purpose?'], answers: ['Mobile Device Management', 'Sets device-level policies for authentication, feature use and conductivity. MDM is a type of software that allows administrators to control the device'] },
      { id: 35, questions: ['What is MAM?', 'Purpose?'], answers: ['Mobile Application Management', 'Sets forth policies for apps that can process corporate data and prevent data transfer to personal apps'] },
      { id: 36, questions: ['Sandbox Solution?'], answers: ['Configures an enterprise-managed container or workspace where the company"s data is stored'] },
      { id: 37, questions: ['DLP', 'What does this detect?'], answers: ['Data Loss Prevention', 'Detects when data is being taken from a device, ensuring it"s only being used in the proper way'] },
      { id: 38, questions: ['ABM', 'Purpose?'], answers: ['Apple Business Manager', 'MAM suite that allows applications from a private repository to devices that are part of the corporate network'] },
      { id: 39, questions: ['Managed Google Play'], answers: ['Managed version of the Google Play store that contains apps that are distributed to employees" devices'] },
      { id: 40, questions: ['MFA', 'What are the Five Factors?'], answers: ['Multifactor Authentication', 'Knowledge Factor, Possession Factor, Inherence Factor, Behaviour Factor, Location Factor'] },
      { id: 41, questions: ['How does voice recognition for the behavior factor work?'], answers: ['Voice recognition systems are not looking at what is said, but at how it is said'] },
      { id: 42, questions: ['Authenticator'], answers: ['Application that serves as a possession factor inside of a mobile device'] },
      { id: 43, questions: ['What are the four types of location services?'], answers: ['Course Positioning, Global Positioning System (GPS), Indoor Positioning System (IPS), Geo-Tracking'] },
      { id: 44, questions: ['Geotagging?'], answers: ['Geotagging is the GPS coordinates inside photos'] },
      { id: 45, questions: ['Three Types of Email Protocols?', 'Respective Ports?'], answers: ['POP3, IMAP, SMTP', 'Port 995, Port 993, Port 465'] },
      { id: 46, questions: ['Which two email protocols are used for receiving/inboud mail?'], answers: ['POP3, IMAP'] },
      { id: 47, questions: ['What email protocol is used for sending/outbound mail?'], answers: ['SMTP'] },
      { id: 48, questions: ['TLS'], answers: ['Transport Layer Security'] },
      { id: 49, questions: ['Unencrypted ports for IMAP, POP3 and SMTP?', 'Encrypted ports?'], answers: ['143, 110, 25', '993, 995, 465'] },
      { id: 50, questions: ['Three main laptop security components?'], answers: ['Biometric Sensor, Near-Field Communication Scanner (NFC Scanner), Kensington Lock (K-Slot/Kensington Security Slot)'] },
      { id: 51, questions: ['What the biometric scanner allow?'], answers: ['Users can have the laptop do a fingerprint scan, facial scan or voice recognition to allow access to the laptop'] },
      { id: 52, questions: ['What is a Kensington Lock?'], answers: ['small port on the side of a laptop that is able to connect a metal braided cable to lock'] },
      { id: 53, questions: ['What are four common upgrades/repairs for laptops?'], answers: ['Replacing the keyboard or touchpad, Upgrading memory, Adding expansion cards, replacing the storage'] }
    ]
  },
  {
    name: 'Domain 3.0 Hardware', cards: [
      { id: 1, questions: ['Printhead is for a...'], answers: ['Inkjet printer'] },
      { id: 2, questions: ['Drummer and toner cartridges are for a...'], answers: ['Laser printer'] },
      { id: 3, questions: ['Why should a printer be left to sit for a while after unboxing?'], answers: ['the hot temperature causes condensation and moisture inside the printer'] },
      { id: 4, questions: ['Two important factors for location of printer?'], answers: ['the location should be well-ventilated and convenient'] },
      { id: 5, questions: ['Two systems employed by printers in office setting?'], answers: ['Print queuing and print authentication'] },
      { id: 6, questions: ['Four methods of printer connectivity?'], answers: ['USB, Ethernet, Wireless, Bluetooth'] },
      { id: 7, questions: ['Benefit of Ethernet printer connetion?'], answers: ['A printer with Ethernet supports DHCP'] },
      { id: 8, questions: ['Two modes of wireless printer connection?', 'What is the key difference?'], answers: ['Infrastructure Mode and Wi-Fi Direct mode', 'Infrastructure mode the printer is connected to the access point, Wi-Fi direct mode the printer is the access point'] },
      { id: 9, questions: ['PDL', 'Define'], answers: ['Page Description Language', 'Used to create a raster file from the print commands that are sent by a software application'] },
      { id: 10, questions: ['Benefit of Vector Graphic?'], answers: ['Size can be changed before printing and won"t lose clarity'] },
      { id: 11, questions: ['PCL'], answers: ['Printer Control Language. Developed by HP and is closely tied to features of different printer models'] },
      { id: 12, questions: ['Postscript'], answers: ['Created by Adobe and is designed to be a device-independent PDL'] },
      { id: 13, questions: ['PDF', 'What does it do?'], answers: ['Portable Document Format', 'Creaed by Adobe which keep"s a file"s original look when viewed or printed on different systems'] },
      { id: 14, questions: ['XPS'], answers: ['XML Paper Specification. Microsoft page description language'] },
      { id: 15, questions: ['What do you need to also install, when installing a printer?'], answers: ['Install the appropriate driver'] },
      { id: 16, questions: ['Two generic formats?'], answers: ['PCL and Postscript'] },
      { id: 17, questions: ['Virtual printers?'], answers: ['XPS and PDF'] },
      { id: 18, questions: ['Four types of print sharing?'], answers: ['Print Server, Microsoft Management Console (MMC), Printer Share, Print Spooler'] },
      { id: 19, questions: ['What is a print server?'], answers: ['Software application or hardware device that manages print requests and printer queue status information'] },
      { id: 20, questions: ['MMC'], answers: ['Microsoft Management Console'] },
      { id: 21, questions: ['Printer Share'], answers: ['Allows to connect a printer using Bluetooth or USB'] },
      { id: 22, questions: ['Print Spooler'], answers: ['Service built into the Windows OS and exists to help print jobs'] },
      { id: 23, questions: ['Three aspects of printer security'], answers: ['User authentication, Audit log, Secured point'] },
      { id: 24, questions: ['Three main scanning services'], answers: ['Scanning, Scanner, Optical Character Recognition (OCR)'] },
      { id: 25, questions: ['OCR', 'Purpose?'], answers: ['Optical Character Recognition', 'Convert scanned text into a digital document that can be manipulated using a word processing program'] },
      { id: 26, questions: ['Image Drum', 'What type of printer?'], answers: ['Main component that creates the image to be applied to the paper', 'Laser'] },
      { id: 27, questions: ['Fuser Assembly', 'What type of printer?'], answers: ['Heats up and melts the toner onto the page to adhere properly to the page', 'Laser'] },
      { id: 28, questions: ['Transfer Belt/Roller', 'What type of printer?'], answers: ['Used as a way to transfer the image from the image drum and become fused', 'Laser'] },
      { id: 29, questions: ['Pickup Roller', 'What type of printer?'], answers: ['Used to pick up the paper from the feed tray and feed it through the system', 'Laser'] },
      { id: 30, questions: ['Paper Separation Pad', 'What type of printer?'], answers: ['Helps the pickup rollers to ensure they only pick up a single piece of paper at a time', 'Laser'] },
      { id: 31, questions: ['Duplexing Assembly'], answers: ['Moves the paper from the front to the back. (Can print of both sides of sheet)'] },
      { id: 32, questions: ['Toner Cartridge'], answers: ['A toner cartridge is a plastic housing that contains toner powder'] },
      { id: 33, questions: ['Do drums or toner last longer?'], answers: ['Drums last longer than toner'] },
      { id: 34, questions: ['What type of memory is used to upgrade laser printer memory?'], answers: ['SODIMM'] },
      { id: 35, questions: ['What are the six steps to printing with a laser printer?'], answers: ['Charging, Exposing, Developing, Transferring, Fusing and Cleaning'] },
      { id: 36, questions: ['What is fusing in laser printing?'], answers: ['The fuser squeezes the paper between a hot roller and a pressure roller'] },
      { id: 37, questions: ['What is the charging voltage measurement?'], answers: ['-600VDC (negative 600 volts DC)'] },
      { id: 38, questions: ['First thing before doing maitenance on laser printer?'], answers: ['Turn off the laser printer and allow it to cool down'] },
      { id: 39, questions: ['What varieties do toner replacement cartridges come in?'], answers: ['Standard toner cartridge has 2500 pages, high-yield cartridge has 6000 pages'] },
      { id: 40, questions: ['What stat should you look at to get an idea of what to replace when?'], answers: ['printer page count'] },
      { id: 41, questions: ['Printer callibration?'], answers: ['Process by which the printer determines the print density or color balance to use'] },
      { id: 42, questions: ['What shouldn"t you use when cleaning laser printers?'], answers: ['compressed air'] },
      { id: 43, questions: ['Inkjet Printers'], answers: ['A type of printer that creates an image on paper using a nozzle or jet on a print head.'] },
      { id: 44, questions: ['High-end Inkjet Printers'], answers: ['Inkjet printers that have seven different cartridges.'] },
      { id: 45, questions: ['Printhead'], answers: ['The device in an inkjet printer that takes droplets of ink and directs them onto the paper.'] },
      { id: 46, questions: ['Piezoelectric/Charge Method'], answers: ['A method of printing that uses a nozzle that reacts to changes in voltage.'] },
      { id: 47, questions: ['Thermal Method'], answers: ['A method of printing used by HP, Canon, and Lexmark printers that relies on heating up the ink in the nozzle of the printhead.'] },
      { id: 48, questions: ['True or False: The thermal method does not require the printhead to be replaced when the ink cartridge is replaced'], answers: ['False'] },
      { id: 49, questions: ['True of False: The Piezoelectric method does not require the printhead to be replaced when the ink cartridge is replaced'], answers: ['True'] },
      { id: 50, questions: ['Roller'], answers: ['The component in an inkjet printer responsible for advancing the paper through the printer'] },
      { id: 51, questions: ['Feeder'], answers: ['The component in an inkjet printer that allows multiple pieces of paper in a tray to be selected one at a time and passed to the roller'] },
      { id: 52, questions: ['Duplexing Assembly'], answers: ['The component in an inkjet printer that allows it to print on both sides of a piece of paper'] },
      { id: 53, questions: ['Carriage Belt/Carriage System'], answers: ['The component in an inkjet printer that allows the printhead to move back and forth across the page'] },
      { id: 54, questions: ['Unidirectional Printing'], answers: ['The printing method in which the printhead applies ink from left to right only'] },
      { id: 55, questions: ['Bi-Directional Printing/Two-Directional Printing'], answers: ['The printing method in which the printhead applies ink from left to right and right to left'] },
      { id: 56, questions: ['Thermal Printer'], answers: ['A type of printer that uses a heating element to create an image'] },
      { id: 57, questions: ['Thermal Paper'], answers: ['A type of paper that is commonly used in high-speed environments with thermal printers'] },
      { id: 58, questions: ['Thermal Ribbon'], answers: ['A type of ribbon that is used in thermal printers to create the heat transfer for printing images. It typically has a mixture of colors (CMYK).'] },
      { id: 59, questions: ['Number of Pins on Thermal Printhead'], answers: ['The number of pins on a thermal printhead determines the quality of the printout. Typically, the higher the number of pins, the better the quality.'] },
      { id: 60, questions: ['Laser Printer'], answers: ['A type of printer that uses a laser to create an image on paper.'] },
      { id: 61, questions: ['Laser Printer DPI'], answers: ['The resolution of a laser printer is typically between 300-600 DPI.'] },
      { id: 62, questions: ['Thermal Printer DPI'], answers: ['The resolution of a thermal printer is typically between 100-300 DPI.'] },
      { id: 63, questions: ['Color Thermal Printer'], answers: ['A type of thermal printer that uses a thermal ribbon to create color images.'] },
      { id: 64, questions: ['Cleaning the Heating Element of a Thermal Printer'], answers: ['Use isopropyl alcohol with a cotton swab to clean the printhead'] },
      { id: 65, questions: ['Impact Printers'], answers: ['A type of printer that uses a printhead with a series of pins to create an image by striking an inked ribbon against the paper'] },
      { id: 66, questions: ['Impact Printer Resolution'], answers: ['The quality of an impact printer is measured based on the quality of the dots it produces. The highest resolution of an impact printer is 240 DPI'] },
      { id: 67, questions: ['Tracks'], answers: ['A series of holes going down the side of the paper with a perforation between the regular paper and tracks. They are used in impact printers to help guide the paper through the printer'] },
      { id: 68, questions: ['Printhead'], answers: ['A device in an impact printer that has a series of pins that make up the dot matrix that forms the image'] },
      { id: 69, questions: ['Ribbon'], answers: ['A fabric or material held within a plastic housing in front of the printhead in an impact printer. The inked ribbon is struck by the printhead to create an image on the paper'] },
      { id: 70, questions: ['Tractor Feed'], answers: ['A type of paper feed mechanism that exists on both sides of the printer and pulls the paper through the printer using tractor fed paper. This is commonly used in impact printers'] },
      { id: 71, questions: ['3D Printer'], answers: ['Type of printer that creates images in three dimensions (height, width, and depth)'] },
      { id: 72, questions: ['Slice'], answers: ['One layer of the overall 3D model'] },
      { id: 73, questions: ['Print bed/Build plate'], answers: ['Flat plate where the material will be extruded and built'] },
      { id: 74, questions: ['Bed/Build Surface'], answers: ['Sheet placed on top of the base plate that hold the object into position while printing'] },
      { id: 75, questions: ['Extruder'], answers: ['Printhead for 3D printers'] },
      { id: 76, questions: ['Fan'], answers: ['Helps to cool down the melted filament to retain the consistency'] },
      { id: 77, questions: ['Filament'], answers: ['Ink for 3D printers (1.75 mm or 3 mm)'] }
    ]
  },
  {
    name: 'Domain 4.0 Virtualization and Cloud Computing', cards: [{ questions: ['what are the three secondary colors'], answers: ['green, orange, purple'] },
    { questions: ['what is the abbreviation for printer colors?', 'What does is stand for?'], answers: ['CMYK', 'cyan, magenta, yellow, black'] }]
  },
  {
    name: 'Domain 5.0 Hardware and Network Troubleshooting', cards: [{ questions: ['what are the three secondary colors'], answers: ['green, orange, purple'] },
    { id: 1, questions: ["How many steps in trouble shooting methodology?", "What are they in order?"], answers: ["Six", "1. Identify the problem 2. Establish a theory of probable cause 3. Test the theory to determine the cause 4. Establish a plan of action to resolve the problem and implement the solution 5. Verify full system functionality 6. Document the findings, actions, and outcome"] },
    { id: 2, questions: ["What are a couple questions to ask for 'Identifying the Problem'?"], answers: ["'What happened?', 'What was the status before?', 'Are there any changes in the system?'"] },
    { id: 3, questions: ["What does a burning smell sometimes indicate?"], answers: ["Damaged processor or motherboard components"] },
    { id: 4, questions: ["What does a clicking or grinding sound sometimes indicate?"], answers: ["Hard drive"] },
    { id: 5, questions: ["What does no spinning fan sometimes indicate?"], answers: ["Power issue or broken fan"] },
    { id: 6, questions: ["What are the four usual outcomes from testing a theory?", "What should you do if there's an issue or unable to solve?"], answers: ["Theory is confirmed, Theory is not confirmed, Lack skills or authority, Unable to solve", "Escalate"] },
    { id: 7, questions: ["Three main avenues for establishing a plan of action"], answers: ["Repair, Replace, Workaround"] },
    { id: 8, questions: ["Power button is not connected properly to the motherboard"], answers: ["Ensuring that the power button is properly connected to the motherboard can help solve power issues."] },
    { id: 9, questions: ["Wall outlet is faulty"], answers: ["Testing the wall outlet with a multimeter or voltmeter can help determine if it's faulty."] },
    { id: 10, questions: ["Power cable to the computer is faulty"], answers: ["Faulty power cables can cause power issues. They have positive, negative, and grounding pins."] },
    { id: 11, questions: ["Power supply is faulty"], answers: ["Faulty power supplies can cause power issues. They provide 12V, 5V, and 3.3V DC power."] },
    { id: 12, questions: ["Origin of 110-120V/60Hz and 220-240V/50Hz"], answers: ["Power in the US or Canada is 110-120V/60Hz, while in Europe or Asia it is 220-240V/50Hz."] },
    { id: 13, questions: ["What connector is found on the bottom of the power supply?", "on the top?"], answers: ["The largest connector", "4,6,8 Pin connectors/SATA/Molex"] },
    { id: 14, questions: ["Power cables from power supply to components are faulty"], answers: ["Detachable power cables can be a cause of power issues. To test them, check each pin on each side of the cable to verify full continuity."] },
    { id: 15, questions: ["Incorrect voltage setting on power supply unit"], answers: ["An incorrect voltage setting on the power supply unit can cause power issues. Make sure the voltage setting is compatible with the components you're using."] },
    { id: 16, questions: ["POST", "purpose?"], answers: ["Power On Self Test", "diagnostic program inside the system firmware"] },
    { id: 17, questions: ["1 Short beep"], answers: ["Normal POST - system is OK"] },
    { id: 18, questions: ["2 Short beeps"], answers: ["POST error - error code shown on screen"] },
    { id: 19, questions: ["No beep"], answers: ["Power supply issue, motherboard problem, or faulty onboard speaker"] },
    { id: 20, questions: ["Continuous beep"], answers: ["Problem with system memory modules or memory controller"] },
    { id: 21, questions: ["Repeating short beeps"], answers: ["Power supply fault or motherboard problem"] },
    { id: 22, questions: ["1 long, 1 short beep"], answers: ["Motherboard problem"] },
    { id: 23, questions: ["1 long beep, 2 or 3 beeps"], answers: ["Video adapter error"] },
    { id: 24, questions: ["3 long beeps"], answers: ["Keyboard issue (check that a key is not depressed)"] },
    { id: 25, questions: ["What can you add to a motherboard to help troubleshoot problems on it?"], answers: ["POST-test expansion card identifies which component on the motherboard is faulty"] },
    { id: 26, questions: ["What is a crash screen?", "Windows", "MAC", "Linux"], answers: ["Displays an error whenever the operating system has issue", "Blue Screen of Death (BSOD), Pinwheel of Death, Kernal Panic"] },
    { id: 27, questions: ["What two main problems can cooling issues cause?"], answers: ["A thermal issue causes intermittent shutdowns or continual rebooting"] },
    { id: 28, questions: ["First step in troubleshooting possible cooling issue?"], answers: ["shut down the system and boot into UEFI or BIOS to check temperature settings"] },
    { id: 29, questions: ["How can you tell if a capacitor is malfunctioning?"], answers: ["You'll probably sense a rancid smell"] },
    { id: 30, questions: ["What are good component benchmarks to minimize performance issues?"], answers: ["3GHz processor, 16GB of RAM, 1 TB hard drive, 1 Gbps networking card"] },
    { id: 31, questions: ["CMOS", "Purpose?"], answers: ["Complementary Metal-Oxide-Semiconductor (CMOS)", "non-volatile type of memory that stores the BIOS settings and is built into the motherboard"] },
    { id: 32, questions: ["NVRAM", "Purpose?"], answers: ["Non-Volatile RAM", "Stores data without constantly being refreshed"] },
    { id: 33, questions: ["What five components can contribute to boot issues?"], answers: ["SSD/Hard Drive, Removable media, Network, Master Boot Record (MBR), GUID Partition Table (GPT)"] },
    { id: 34, questions: ["BCD"], answers: ["Boot Configuration Data"] },
    { id: 35, questions: ["MBR", "Purpose?"], answers: ["Master Boot Record", "Legacy method of providing the boot information"] },
    { id: 36, questions: ["GPT", "What is it?"], answers: ["GUID Partition Table", "specialized boot scheme with modern advantages"] },
    { id: 37, questions: ["Three common issues for booting up OS"], answers: ["Bootable device not found, Operating system not found, Invalid drive specification"] },
    { id: 38, questions: ["Basic way to check if internal storage device is working properly"], answers: ["looking, listening and feeling"] },
    { id: 39, questions: ["Two types of storage devices"], answers: ["Hard Disk Drive (HDD), Solid-State Device (SSD)"] },
    { id: 40, questions: ["Advantage/disadvantage of HDD"], answers: ["low-cost, slower speed"] },
    { id: 41, questions: ["Advantage/disadvantage of SSD"], answers: ["higher speed, higher cost"] },
    { id: 42, questions: ["Which type of storage device has a limit on reads and writes?"], answers: ["SSD"] },
    { id: 43, questions: ["What do clicking or grinding sounds indicate?"], answers: ["Those are signs of a hard disk mechanical problem"] },
    { id: 44, questions: ["How do you prevent the disk from being used as a swap or page file?"], answers: ["Add more physical memory to the computer"] },
    { id: 45, questions: ["How can you see if the device is detected?"], answers: ["Use your computer's disk management tools"] },
    { id: 46, questions: ["Sectors - ? Blocks - ?"], answers: ["Windows/Linux, Solid-State Device (SSD)"] },
    { id: 47, questions: ["SMART", "Purpose"], answers: ["Self-Monitoring, Analysis and Reporting Technology", "Self-diagnostic program that alerts the OS if there is a failure"] },
    { id: 48, questions: ["What are the six main things SMART will monitor"], answers: ["Read rate error, spin-up time, reallocated sector count, seek error rate, power-on hours, temperature"] },
    { id: 49, questions: ["IOPS, Which type of drive has a higher IOPS?"], answers: ["Input/Output Operations per second", "SDD"] },
    { id: 50, questions: ["What type of storage drive is de-fragmentation useful for?"], answers: ["HDD"] },
    { id: 51, questions: ["Two types of RAID failures", "What is the usual term for repairing a RAID?"], answers: ["Single disk failure and full RAID failure", "rebuild"] },
    { id: 52, questions: ["What are the five common cables that carry a digital video signal?", "Which three of these cables carry audio?"], answers: ["HDMI, DisplayPort, Thunderbolt, DVI-D, DVI-I", "HDMI, DisplayPort and Thunderbolt"] },
    { id: 53, questions: ["Five most common reasons a "], answers: ["1. Broken cable, 2. Cables are not properly inserted, 3. Cheap cable, 4. Incorrect data source selected, 5. HDMI device issue"] },
    { id: 54, questions: ["True or False: Higher quality HDMI cables support higher-speed and bandwidth?"], answers: ["True"] },
    { id: 55, questions: ["HDCP", "Purpose?"], answers: ["High-Bandwidth Digital Content Protection", "Protects the audio and video signals between systems over HDMI and DisplayPort"] },
    { id: 56, questions: ["What are three common projector issues?"], answers: ["Dim images, No images, and frequent shut down or restart"] },
    { id: 57, questions: ["What is a common reason for a projector to automatically shutdown?"], answers: ["There is no source input connected"] },
    { id: 58, questions: ["What is the average lifespan range for projector bulbs?"], answers: ["500-2000 hours"] },
    { id: 59, questions: ["True or False: It's not necessary to let a projector cool down before changing out the bulb?"], answers: ["False. The projector needs 15 to 30 minutes to cool down, otherwise you could get burned by the bulb"] },
    { id: 60, questions: ["What are the five common video quality issues?"], answers: ["Dim images, fuzzy images, flashing screens, dead pixels, burn-in"] },
    { id: 61, questions: ["Fix for dim images?"], answers: ["Increase the brightness or contrast controls on the monitor"] },
    { id: 62, questions: ["Fix for fuzzy images?"], answers: ["Raise the resolution from the computer to match the monitors resolution specs"] },
    { id: 63, questions: ["How do you fix a dead pixel?"], answers: ["There is no fix"] },
    { id: 64, questions: ["What causes burn-in?", "Preventative measures?"], answers: ["Burn-in occurs when the same static picture is displayed on a screen for a long time", "Run an animated screen saver or turn off when inactive"] },
    { id: 65, questions: ["What is the range of color bit palettes?", "What bit-depths are known as true color and deep color?"], answers: ["8-bit to 32-bit", "24-bit is true and 32-bit is deep"] },
    { id: 66, questions: ["Five things to look at when troubleshooting wired connectivity issues?"], answers: ["Physical connection, cable length, interference, port flapping, the link light shows a valid link"] },
    { id: 67, questions: ["What does the network activity light show for different speeds?"], answers: ["10 Mbps (off), 100 Mbps (Orange), 1000 Mbps (Green)"] },
    { id: 68, questions: ["What can you use to increase a connectivity signal?"], answers: ["a repeater"] },
    { id: 69, questions: ["What are external sources of interference for wired connections?", "what type of network cable should cables near power lines use?"], answers: ["power lines, fluorescent lighting, motors, generators", "fiber optic connections"] },
    { id: 70, questions: ["What causes port flapping?", "what does it do?"], answers: ["caused by an intermittent connectivity issue between the client and the network switch", "causes a switch port's state to fluctuate between up and down within concise periods of time"] },
    { id: 71, questions: ["Half duplex?", "Full duplex?"], answers: ["network that sends OR receives information", "network that sends or receives information at the same time"] },
    { id: 72, questions: ["Four common causes of network performance issues"], answers: ["1. Mismatch in the duplex setting, 2. Mismatch in the speed setting, 3. Network adapter drivers are out of date, 4. Malware infection"] },
    { id: 73, questions: ["What are four common wireless connectivity issues?"], answers: ["Intermittent wireless connectivity, Signal interference, low signal strength, standards mismatch"] },
    { id: 74, questions: ["Common cause for intermittent wireless connectivity?"], answers: ["Connected or disconnected network"] },
    { id: 75, questions: ["Common cause for intermittent wired connectivity?"], answers: ["upstate to a downstate of switch port"] },
    { id: 76, questions: ["What are the three channels used to spread out wireless signal and reduce change of interference?"], answers: ["1, 6 and 11"] },
    { id: 77, questions: ["What for wireless router types are less prone to signal interference?"], answers: ["a, n, ac, ax"] },
    { id: 78, questions: ["RSSI", "Purpose?", "How is it displayed?"], answers: ["Received Signal Strength Indicator", "Used to measure the signal strength based on an index level and gives a value in decibels (dB)", "in negative decibels"] },
    { id: 79, questions: ["Three ways to increase signal strength"], answers: ["Increase the power of transmission, increase the antenna size, move closer to the source"] },
    { id: 80, questions: ["5 GHz applies to which types of routers?"], answers: ["a, n, ac, ax"] },
    { id: 81, questions: ["2.4 GHz applies to which types of routers?"], answers: ["b, g and n"] },
    { id: 82, questions: ["VoIP", "Define"], answers: ["Voice Over Internet Protocol", "Set of protocols that are used to send streaming voice and video in real time"] },
    { id: 83, questions: ["Define Latency", "What range should you aim for with latency?"], answers: ["Time it takes for a signal to reach the intended client", "50 to 100 milliseconds"] },
    { id: 84, questions: ["What is jitter?", "when does jitter begin to occur?"], answers: ["Measurement of the variation in delay over time", "when latency increases by up to 30 to 50 milliseconds, it starts to have jitter"] },
    { id: 85, questions: ["In regards to VoIP, what does Quality of Service (Qos) allow you to set?"], answers: ["You can set the QoS to prioritize voice traffic"] },
    { id: 86, questions: ["QoS"], answers: ["Quality of Service"] },
    { id: 87, questions: ["Two things to check when having limited connectivity issues:"], answers: ["1. Affects one network client 2. VLAN is properly configured"] },
    { id: 88, questions: ["What are three common mobile power issues?"], answers: ["Poor battery health, charging issues, swollen batteries"] },
    { id: 89, questions: ["What can cause poor battery health?"], answers: ["Age. As batteries age, the maximum charge they can hold decreases"] },
    { id: 90, questions: ["What causes swollen batteries?"], answers: ["Swollen batteries are caused by overcharging"] },
    { id: 91, questions: ["What are three common mobile hardware issues?"], answers: ["Overheating damage, liquid damage, physical port damage"] },
    { id: 92, questions: ["Five steps to fixing liquid damage?"], answers: ["Dry off excess liquid, power off the device, disassemble the device, clean the circuit boards and contacts, replace the battery"] },
    { id: 93, questions: ["How to fix physical port damage?"], answers: ["To fix the damaged port, remove the port and replace it"] },
    { id: 94, questions: ["Common mobile display issues?"], answers: ["Broken screens, dim images, digitizer issues, calibration issues"] },
    { id: 95, questions: ["What are the four layers of a mobile screen?"], answers: ["Glass, Digitizer, Screen, Backlight"] },
    { id: 96, questions: ["What two components should you consider when troubleshooting a dim image?"], answers: ["backlight, inverter"] },
    { id: 97, questions: ["What usually causes a digitizer to fail?"], answers: ["Digitizers fail because of shock damage from dropping or liquid damage"] },
    { id: 98, questions: ["What two things should you do when troubleshooting a calibration issue?"], answers: ["Check the touch pad sensitivity and observe the user"] },
    { id: 99, questions: ["What are four mobile connectivity issues caused by physical issues?", "How far away should you operate from the access point to maintain a good connection?"], answers: ["Make sure the device is connected to the right SSID, make sure the right password is being used, move closer to the wireless access point, might need a higher gain antenna attached", "Operate 30 to 50 meters away from the wireless access point to maintain a good connection"] },
    { id: 100, questions: ["Four common software configuration checks for mobile connectivity?"], answers: ["bluetooth enabled, properly paired, adequate battery, right range"] },
    { id: 101, questions: ["What is Bluetooth's maximum range?"], answers: ["Up to 10 meters"] },
    { id: 102, questions: ["NIC", "what to check if it's not working properly?"], answers: ["Network Interface Card", "Make sure it's properly connected to the antennas"] },
    { id: 103, questions: ["What five concepts are associated with mobile malware infections?"], answers: ["antivirus or anti-malware solution, excessive power drain, significant data transmission, camera and microphone, asking for additional permissions"] },
    { id: 104, questions: ["Most fool-proof way to rid mobile device of malware?"], answers: ["1. Back up the data, 2. Format the device and re-install the base operating system"] },
    { id: 105, questions: [""], answers: [""] },
    { id: 106, questions: [""], answers: [""] },
    { id: 107, questions: [""], answers: [""] },
    ]
  }
]