export const decks = [
  {
    name: 'Domain 1.0 Mobile Devices (and Laptops)', cards: [
      { id: 1, questions: ['Capacitive Touch Screen', 'True or False: One touch at a time?'], answers: ['Any touchscreen that works by seeing the distortion in an electrostatic field', 'True. A single tactile input is one touch at a time'] },
      { id: 2, questions: ['Multi-Touch Screen'], answers: ['Can process two or more contact points simultaneously'] },
      { id: 3, questions: ['What does LCD stand for?', 'What does it mean?'], answers: ['Liquid-Crystal Display', 'Uses liquid crystal where the properties can change with the application of voltage'] },
      { id: 4, questions: ['Explain Pixel (Picture Element)'], answers: ['Individual point on a screen inside of a display'] },
      { id: 5, questions: ['What is a TFT?', 'What is it referred to as?'], answers: ['A thin-film transistor', 'an LCD panel'] },
      { id: 6, questions: ['What is a Twisted Nematic (TN)?', "What's its advantage?"], answers: ['Contains crystals that twist or untwist in response to voltage being applied or removed', 'TN support fast response time in comparison to other TFT technologies and displays'] },
      { id: 7, questions: ['what does IPS stand for?', 'What does it do?', 'True or False: It support 180 degree viewing angles?'], answers: ['In-Plane Switching', 'Uses crystals that rotate to be able to deliver color', 'False. It can support 178degree horizontal and vertical viewing angles'] },
      { id: 8, questions: ['What is VA?', 'What is its advantage?'], answers: ['Vertical Alignment', 'A VA display has a contrast ratio of two to three times better than a standard IPS display'] },
      { id: 9, questions: ['What does CCFL stand for?', 'How does it work?', 'Does it require AC or DC voltage?'], answers: ['Cold Cathode Fluorescent Lamp', 'Lamp that sits behind the display and lights up the liquid crystal display to show the colors and images properly on screen', 'CCFL requires AC voltage'] },
      { id: 10, questions: ['What does LED mean?', 'what is it?', 'advantages?'], answers: ['Light-Emitting Diode', 'Newer form of light that uses direct current (DC)', 'use of LEDs use less power, leading to longer battery life and better performance'] },
      { id: 11, questions: ['What does OLED mean?', 'What are three differences to LED'], answers: ['Organic Light-Emitting Diode', 'Each pixel has its own separate LED that provides the light', 'OLEDs can be made from plastic', 'OLEDs can be folded, rolled up, or manipulated to create different shapes and sizes of displays'] },
      { id: 12, questions: ['What are the three main mobile device components?'], answers: ['Digitizer, Accelerometer, and Gyroscope'] },
      {
        id: 13, questions: ['What is the digitizer?', 'what is its purpose?'
        ], answers: ['layer sandwiched between protective glass and the display panel inside of a touchscreen display', 'Haptic feedback provides a form or touch responsiveness from the display back to the end-user']
      },
      { id: 14, questions: ['What is the accelerometer?'], answers: ['Combination device that uses hardware and software to measure the velocity, rotation, and shaking of a mobile device'] },
      { id: 15, questions: ['What is a gyroscope?', 'what are the reasons its an improvement?'], answers: ['An improved version of the basic accelerometer', 'Detects pitch (Y), roll (X), and yaw (Z). Performs actions and stabilizes images'] },
      { id: 16, questions: ['Name 5 out of 6 Mobile device accessories'], answers: ['Track pad, drawing pad, microphone, speaker, headset, digital camera'] },
      { id: 17, questions: ['What are the two types of pad devices that can be used with mobile?', 'What does the track pad do?'], answers: ['Track pad and Drawing pad', 'controls the cursor on the screen'] },
      { id: 18, questions: ['What two devices does an external headset combine?'], answers: ['headsets combine both the microphone and the speaker'] },
      { id: 19, questions: ['True of False: Wireless connectivity is slower on smaller devices than it is on larger devices?'], answers: ['True'] },
      { id: 20, questions: ['What are the two main types of wireless cellular technology?', 'What is the more powerful and flexible technology?'], answers: ['GSM and CDMA', 'CDMA'] },
      { id: 21, questions: ['What does PRL mean?', 'What does this contain?', 'True or False: restrictions vary based on model?'], answers: ['Preferred Roaming List', 'This contains all the information about different cellular towers', 'True'] },
      { id: 22, questions: ['What are the two types of short-range connection options for mobile?'], answers: ['Bluetooth and Near-Field Communication'] },
      { id: 23, questions: ['What are the four main types of wired mobile connectivity?'], answers: ['Lightning Cable (Apple), USB-C, DB9 Cable, Universal Asynchronous Receiver-Transmitter (UART)'] },
      { id: 24, questions: ['What is the difference between a port replicator and a docking station?'], answers: ['Port replicators are port mirrors and docking stations are a port mirror with ADDITIONAL points'] },
      { id: 25, questions: ['Which devices use Android and iOS, respectively?', 'Which is open-source, closed-source?'], answers: ['any non-Apple device, iPads and iPhones', 'Android is open, iOS is closed'] },
      { id: 26, questions: ['What programming languages do iOS apps use?', 'What programming languages do Android apps use?'], answers: ['Swift and Xcode', 'Java and Android Studio'] },
      { id: 27, questions: ['Benefit of Microsoft 365 to mobile?'], answers: ['Provides the ability to have office productivity software and a large amount of storage space in the cloud (OneDrive)'] },
      { id: 28, questions: ['Define Mobile Device Synchronization/Sync'], answers: ['Act of copying data back and forth between different devices'] },
      { id: 29, questions: ['What is a vCard?'], answers: ['Standard contact format and is widely supported by most address books and software applications'] },
      { id: 30, questions: ['Is POP3 a good choice for synchronization?'], answers: ['No, oldest format and does not support the synchronization across devices'] },
      { id: 31, questions: ['Which email protocols can manage the state of an email?'], answers: ['IMAP and Exchange'] },
      { id: 32, questions: ['What are the three synchrozation choices?'], answers: ['synchronization to the cloud, to the computer and with the automobile'] },
      { id: 33, questions: ['What is EMM?', 'Meaning?'], answers: ['Enterprise Mobility Management', 'Class of software designed to apply security policies for use on mobile devices'] },
      { id: 34, questions: ['What is MDM?', 'Purpose?'], answers: ['Mobile Device Management', 'Sets device-level policies for authentication, feature use and conductivity. MDM is a type of software that allows administrators to control the device'] },
      { id: 35, questions: ['What is MAM?', 'Purpose?'], answers: ['Mobile Application Management', 'Sets forth policies for apps that can process corporate data and prevent data transfer to personal apps'] },
      { id: 36, questions: ['Sandbox Solution?'], answers: ['Configures an enterprise-managed container or workspace where the company"s data is stored'] },
      { id: 37, questions: ['DLP', 'What does this detect?'], answers: ['Data Loss Prevention', 'Detects when data is being taken from a device, ensuring it"s only being used in the proper way'] },
      { id: 38, questions: ['ABM', 'Purpose?'], answers: ['Apple Business Manager', 'MAM suite that allows applications from a private repository to devices that are part of the corporate network'] },
      { id: 39, questions: ['Managed Google Play'], answers: ['Managed version of the Google Play store that contains apps that are distributed to employees" devices'] },
      { id: 40, questions: ['MFA', 'What are the Five Factors?'], answers: ['Multifactor Authentication', 'Knowledge Factor, Possession Factor, Inherence Factor, Behaviour Factor, Location Factor'] },
      { id: 41, questions: ['How does voice recognition for the behavior factor work?'], answers: ['Voice recognition systems are not looking at what is said, but at how it is said'] },
      { id: 42, questions: ['Authenticator'], answers: ['Application that serves as a possession factor inside of a mobile device'] },
      { id: 43, questions: ['What are the four types of location services?'], answers: ['Course Positioning, Global Positioning System (GPS), Indoor Positioning System (IPS), Geo-Tracking'] },
      { id: 44, questions: ['Geotagging?'], answers: ['Geotagging is the GPS coordinates inside photos'] },
      { id: 45, questions: ['Three Types of Email Protocols?', 'Respective Ports?'], answers: ['POP3, IMAP, SMTP', 'Port 995, Port 993, Port 465'] },
      { id: 46, questions: ['Which two email protocols are used for receiving/inboud mail?'], answers: ['POP3, IMAP'] },
      { id: 47, questions: ['What email protocol is used for sending/outbound mail?'], answers: ['SMTP'] },
      { id: 48, questions: ['TLS'], answers: ['Transport Layer Security'] },
      { id: 49, questions: ['Unencrypted ports for IMAP, POP3 and SMTP?', 'Encrypted ports?'], answers: ['143, 110, 25', '993, 995, 465'] },
      { id: 50, questions: ['Three main laptop security components?'], answers: ['Biometric Sensor, Near-Field Communication Scanner (NFC Scanner), Kensington Lock (K-Slot/Kensington Security Slot)'] },
      { id: 51, questions: ['What the biometric scanner allow?'], answers: ['Users can have the laptop do a fingerprint scan, facial scan or voice recognition to allow access to the laptop'] },
      { id: 52, questions: ['What is a Kensington Lock?'], answers: ['small port on the side of a laptop that is able to connect a metal braided cable to lock'] },
      { id: 53, questions: ['What are four common upgrades/repairs for laptops?'], answers: ['Replacing the keyboard or touchpad, Upgrading memory, Adding expansion cards, replacing the storage'] }
    ]
  },
  {
    name: 'Domain 2.0 Networking', cards: [{ questions: ['what are the three secondary colors'], answers: ['green, orange, purple'] },
    { questions: ['what is the abbreviation for printer colors?', 'What does is stand for?'], answers: ['CMYK', 'cyan, magenta, yellow, black'] }]
  },
  {
    name: 'Domain 3.0 Hardware', cards: [
      { id: 1, questions: ['Printhead is for a...'], answers: ['Inkjet printer'] },
      { id: 2, questions: ['Drummer and toner cartridges are for a...'], answers: ['Laser printer'] },
      { id: 3, questions: ['Why should a printer be left to sit for a while after unboxing?'], answers: ['the hot temperature causes condensation and moisture inside the printer'] },
      { id: 4, questions: ['Two important factors for location of printer?'], answers: ['the location should be well-ventilated and convenient'] },
      { id: 5, questions: ['Two systems employed by printers in office setting?'], answers: ['Print queuing and print authentication'] },
      { id: 6, questions: ['Four methods of printer connectivity?'], answers: ['USB, Ethernet, Wireless, Bluetooth'] },
      { id: 7, questions: ['Benefit of Ethernet printer connetion?'], answers: ['A printer with Ethernet supports DHCP'] },
      { id: 8, questions: ['Two modes of wireless printer connection?', 'What is the key difference?'], answers: ['Infrastructure Mode and Wi-Fi Direct mode', 'Infrastructure mode the printer is connected to the access point, Wi-Fi direct mode the printer is the access point'] },
      { id: 9, questions: ['PDL', 'Define'], answers: ['Page Description Language', 'Used to create a raster file from the print commands that are sent by a software application'] },
      { id: 10, questions: ['Benefit of Vector Graphic?'], answers: ['Size can be changed before printing and won"t lose clarity'] },
      { id: 11, questions: ['PCL'], answers: ['Printer Control Language. Developed by HP and is closely tied to features of different printer models'] },
      { id: 12, questions: ['Postscript'], answers: ['Created by Adobe and is designed to be a device-independent PDL'] },
      { id: 13, questions: ['PDF', 'What does it do?'], answers: ['Portable Document Format', 'Creaed by Adobe which keep"s a file"s original look when viewed or printed on different systems'] },
      { id: 14, questions: ['XPS'], answers: ['XML Paper Specification. Microsoft page description language'] },
      { id: 15, questions: ['What do you need to also install, when installing a printer?'], answers: ['Install the appropriate driver'] },
      { id: 16, questions: ['Two generic formats?'], answers: ['PCL and Postscript'] },
      { id: 17, questions: ['Virtual printers?'], answers: ['XPS and PDF'] },
      { id: 18, questions: ['Four types of print sharing?'], answers: ['Print Server, Microsoft Management Console (MMC), Printer Share, Print Spooler'] },
      { id: 19, questions: ['What is a print server?'], answers: ['Software application or hardware device that manages print requests and printer queue status information'] },
      { id: 20, questions: ['MMC'], answers: ['Microsoft Management Console'] },
      { id: 21, questions: ['Printer Share'], answers: ['Allows to connect a printer using Bluetooth or USB'] },
      { id: 22, questions: ['Print Spooler'], answers: ['Service built into the Windows OS and exists to help print jobs'] },
      { id: 23, questions: ['Three aspects of printer security'], answers: ['User authentication, Audit log, Secured point'] },
      { id: 24, questions: ['Three main scanning services'], answers: ['Scanning, Scanner, Optical Character Recognition (OCR)'] },
      { id: 25, questions: ['OCR', 'Purpose?'], answers: ['Optical Character Recognition', 'Convert scanned text into a digital document that can be manipulated using a word processing program'] },
      { id: 26, questions: ['Image Drum', 'What type of printer?'], answers: ['Main component that creates the image to be applied to the paper', 'Laser'] },
      { id: 27, questions: ['Fuser Assembly', 'What type of printer?'], answers: ['Heats up and melts the toner onto the page to adhere properly to the page', 'Laser'] },
      { id: 28, questions: ['Transfer Belt/Roller', 'What type of printer?'], answers: ['Used as a way to transfer the image from the image drum and become fused', 'Laser'] },
      { id: 29, questions: ['Pickup Roller', 'What type of printer?'], answers: ['Used to pick up the paper from the feed tray and feed it through the system', 'Laser'] },
      { id: 30, questions: ['Paper Separation Pad', 'What type of printer?'], answers: ['Helps the pickup rollers to ensure they only pick up a single piece of paper at a time', 'Laser'] },
      { id: 31, questions: ['Duplexing Assembly'], answers: ['Moves the paper from the front to the back. (Can print of both sides of sheet)'] },
      { id: 32, questions: ['Toner Cartridge'], answers: ['A toner cartridge is a plastic housing that contains toner powder'] },
      { id: 33, questions: ['Do drums or toner last longer?'], answers: ['Drums last longer than toner'] },
      { id: 34, questions: ['What type of memory is used to upgrade laser printer memory?'], answers: ['SODIMM'] },
      { id: 35, questions: ['What are the six steps to printing with a laser printer?'], answers: ['Charging, Exposing, Developing, Transferring, Fusing and Cleaning'] },
      { id: 36, questions: ['What is fusing in laser printing?'], answers: ['The fuser squeezes the paper between a hot roller and a pressure roller'] },
      { id: 37, questions: ['What is the charging voltage measurement?'], answers: ['-600VDC (negative 600 volts DC)'] },
      { id: 38, questions: ['First thing before doing maitenance on laser printer?'], answers: ['Turn off the laser printer and allow it to cool down'] },
      { id: 39, questions: ['What varieties do toner replacement cartridges come in?'], answers: ['Standard toner cartridge has 2500 pages, high-yield cartridge has 6000 pages'] },
      { id: 40, questions: ['What stat should you look at to get an idea of what to replace when?'], answers: ['printer page count'] },
      { id: 41, questions: ['Printer callibration?'], answers: ['Process by which the printer determines the print density or color balance to use'] },
      { id: 42, questions: ['What shouldn"t you use when cleaning laser printers?'], answers: ['compressed air'] },
      { id: 43, questions: ['Inkjet Printers'], answers: ['A type of printer that creates an image on paper using a nozzle or jet on a print head.'] },
      { id: 44, questions: ['High-end Inkjet Printers'], answers: ['Inkjet printers that have seven different cartridges.'] },
      { id: 45, questions: ['Printhead'], answers: ['The device in an inkjet printer that takes droplets of ink and directs them onto the paper.'] },
      { id: 46, questions: ['Piezoelectric/Charge Method'], answers: ['A method of printing that uses a nozzle that reacts to changes in voltage.'] },
      { id: 47, questions: ['Thermal Method'], answers: ['A method of printing used by HP, Canon, and Lexmark printers that relies on heating up the ink in the nozzle of the printhead.'] },
      { id: 48, questions: ['True or False: The thermal method does not require the printhead to be replaced when the ink cartridge is replaced'], answers: ['False'] },
      { id: 49, questions: ['True of False: The Piezoelectric method does not require the printhead to be replaced when the ink cartridge is replaced'], answers: ['True'] },
      { id: 50, questions: ['Roller'], answers: ['The component in an inkjet printer responsible for advancing the paper through the printer'] },
      { id: 51, questions: ['Feeder'], answers: ['The component in an inkjet printer that allows multiple pieces of paper in a tray to be selected one at a time and passed to the roller'] },
      { id: 52, questions: ['Duplexing Assembly'], answers: ['The component in an inkjet printer that allows it to print on both sides of a piece of paper'] },
      { id: 53, questions: ['Carriage Belt/Carriage System'], answers: ['The component in an inkjet printer that allows the printhead to move back and forth across the page'] },
      { id: 54, questions: ['Unidirectional Printing'], answers: ['The printing method in which the printhead applies ink from left to right only'] },
      { id: 55, questions: ['Bi-Directional Printing/Two-Directional Printing'], answers: ['The printing method in which the printhead applies ink from left to right and right to left'] },
      { id: 56, questions: ['Thermal Printer'], answers: ['A type of printer that uses a heating element to create an image'] },
      { id: 57, questions: ['Thermal Paper'], answers: ['A type of paper that is commonly used in high-speed environments with thermal printers'] },
      { id: 58, questions: ['Thermal Ribbon'], answers: ['A type of ribbon that is used in thermal printers to create the heat transfer for printing images. It typically has a mixture of colors (CMYK).'] },
      { id: 59, questions: ['Number of Pins on Thermal Printhead'], answers: ['The number of pins on a thermal printhead determines the quality of the printout. Typically, the higher the number of pins, the better the quality.'] },
      { id: 60, questions: ['Laser Printer'], answers: ['A type of printer that uses a laser to create an image on paper.'] },
      { id: 61, questions: ['Laser Printer DPI'], answers: ['The resolution of a laser printer is typically between 300-600 DPI.'] },
      { id: 62, questions: ['Thermal Printer DPI'], answers: ['The resolution of a thermal printer is typically between 100-300 DPI.'] },
      { id: 63, questions: ['Color Thermal Printer'], answers: ['A type of thermal printer that uses a thermal ribbon to create color images.'] },
      { id: 64, questions: ['Cleaning the Heating Element of a Thermal Printer'], answers: ['Use isopropyl alcohol with a cotton swab to clean the printhead'] },
      { id: 65, questions: ['Impact Printers'], answers: ['A type of printer that uses a printhead with a series of pins to create an image by striking an inked ribbon against the paper'] },
      { id: 66, questions: ['Impact Printer Resolution'], answers: ['The quality of an impact printer is measured based on the quality of the dots it produces. The highest resolution of an impact printer is 240 DPI'] },
      { id: 67, questions: ['Tracks'], answers: ['A series of holes going down the side of the paper with a perforation between the regular paper and tracks. They are used in impact printers to help guide the paper through the printer'] },
      { id: 68, questions: ['Printhead'], answers: ['A device in an impact printer that has a series of pins that make up the dot matrix that forms the image'] },
      { id: 69, questions: ['Ribbon'], answers: ['A fabric or material held within a plastic housing in front of the printhead in an impact printer. The inked ribbon is struck by the printhead to create an image on the paper'] },
      { id: 70, questions: ['Tractor Feed'], answers: ['A type of paper feed mechanism that exists on both sides of the printer and pulls the paper through the printer using tractor fed paper. This is commonly used in impact printers'] },
      { id: 71, questions: ['3D Printer'], answers: ['Type of printer that creates images in three dimensions (height, width, and depth)'] },
      { id: 72, questions: ['Slice'], answers: ['One layer of the overall 3D model'] },
      { id: 73, questions: ['Print bed/Build plate'], answers: ['Flat plate where the material will be extruded and built'] },
      { id: 74, questions: ['Bed/Build Surface'], answers: ['Sheet placed on top of the base plate that hold the object into position while printing'] },
      { id: 75, questions: ['Extruder'], answers: ['Printhead for 3D printers'] },
      { id: 76, questions: ['Fan'], answers: ['Helps to cool down the melted filament to retain the consistency'] },
      { id: 77, questions: ['Filament'], answers: ['Ink for 3D printers (1.75 mm or 3 mm)'] }
    ]
  },
  {
    name: 'Domain 4.0 Virtualization and Cloud Computing', cards: [{ questions: ['what are the three secondary colors'], answers: ['green, orange, purple'] },
    { questions: ['what is the abbreviation for printer colors?', 'What does is stand for?'], answers: ['CMYK', 'cyan, magenta, yellow, black'] }]
  },
  {
    name: 'Domain 5.0 Hardware and Network Troubleshooting', cards: [{ questions: ['what are the three secondary colors'], answers: ['green, orange, purple'] },
    { questions: ['what is the abbreviation for printer colors?', 'What does is stand for?'], answers: ['CMYK', 'cyan, magenta, yellow, black'] }]
  }
]